#!/bin/sh
function run
{
	echo -n '> '
	echo "$*"
	"$@"
}

function sighandler
{
	export SAVED_RETCODE=$?
	trap : EXIT
	run rm ports.tar.gz
	exit $SAVED_RETCODE
}
trap 'sighandler' INT EXIT TERM HUP

run cd /tmp
run curl -L \
	$(cat /etc/installurl)/$(uname -r)/ports.tar.gz \
	-o ports.tar.gz \

if [ ! -w /usr ]; then
	run doas tar xzf ports.tar.gz -C /usr
	run doas pkg_add portslist
else
	run tar xzf ports.tar.gz -C /usr
	run pkg_add portslist
fi

# vim:ts=4 noet:
