#!/bin/sh

# xinput set-button-map 'TPPS/2 Elan TrackPoint' 1 0 3
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.001
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xsetroot -cursor_name left_ptr &
xset r rate 300 20

xmodmap -e 'add Lock = XF86Favorites ' && \
xmodmap -e 'remove Lock = Caps_Lock' && \
xmodmap -e 'remove control = Control_L' && \
xmodmap -e 'keysym Caps_Lock = Control_L' && \
xmodmap -e 'add control = Control_L' && \
pkill xcape
xcape -t 300 -e 'Control_L=XF86Favorites'


pkill sxhkd
sh -c 'sxhkd &> /dev/null &'

# pkill -q /usr/lib/gsd-xsettings
# /usr/lib/gsd-xsettings &> /dev/null &
# disown


pkill -f 'this is a comment for my borderer'
sh -c '
	IFS=:
	echo $IFS
	bspc subscribe | while read -r REPORT; do
		for WORD in $REPORT; do
			if [ "$WORD" = "T@" ]; then
				bspc config border_width 10
				break
			else
				bspc config border_width 0
			fi
		done
	done;
	# this is a comment for my borderer
' &
disown

bspc config border_width        0
bspc config window_gap          20
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config initial_polarity	first_child

bspc config normal_border_color '#000000'
bspc config focused_border_color '#ff0000'

# bspc config swallow_first_click true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config merge_overlapping_monitors true
bspc config ignore_ewmh_fullscreen true
# bspc config pointer_follows_focus true

# NOTE: use xprop to get these values
bspc rule -a VirtualBoxVM state=floating
bspc rule -a "VirtualBox Machine" state=tiled
bspc rule -a jome state=floating
bspc rule -a '*:*:Picture-in-Picture' state=floating layer=above sticky=on focus=off
bspc rule -a '*:*:Picture-in-picture' state=floating layer=above sticky=on focus=off
bspc rule -a Safeeyes state=floating layer=above fullscreen=off focus=off
bspc rule -a Clipster layer=above
bspc rule -a mpv state=pseudo_tiled
bspc rule -a GParted state=floating layer=above
bspc rule -a feh state=floating layer=above focus=on
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled

pkill xmousepasteblock
sh -c 'xmousepasteblock &> /dev/null &'

pkill clipster
sh -c 'clipster -d &> /dev/null &'


# safeeyes -e &> /dev/null &
# sh -c "$(which safeeyes) -e &> /dev/null &"


# if pidof acpid; then true; else zsh <<< "kitty sh -c 'echo \"Starting acpid ...\"; sudo acpid' &"; fi &
# if [[ -r /dev/video0 || -r /dev/video1 ]]; then zsh <<< "kitty sh -c 'echo \"Disabling camera ...\"; sudo chmod -r /dev/video*' &"; fi &

pgrep urxvtd >/dev/null || urxvtd -q -f -o

# pkill -q picom
# picom --experimental-backends &> /dev/null &

exec /bin/sh -c 'bspc subscribe report | tcc -run ~/.config/bspwm/desktop_manager.c | /bin/sh'
